# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_data_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
